# Generated by Django 4.1.5 on 2023-01-05 17:18

from django.db import migrations
def insert_sample_restaurants(apps,schema_editor):
    Restaurant = apps.get_model('Elite_eats_app', 'Restaurant')
    Restaurant.objects.create(name="The Chelsea House", address="235 Ninth Ave", city="New York", state="NY", zip_code="10001")

class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sample_restaurants)
    ]
