# Generated by Django 4.1.5 on 2023-01-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0003_tag_remove_restaurant_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Tag',
            new_name='tag',
        ),
    ]
