# Generated by Django 4.1.4 on 2023-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0005_post_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.CharField(max_length=1500),
        ),
    ]
