# Generated by Django 4.1.5 on 2023-01-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0006_alter_post_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Elite_eats_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
                ('restaurant', models.ManyToManyField(blank=True, to='Elite_eats_app.restaurant')),
            ],
        ),
    ]
