# Generated by Django 4.1.5 on 2023-01-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0007_image_tag_alter_restaurant_options_post_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='images/'),
        ),
    ]
