# Generated by Django 4.1.7 on 2023-03-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0007_image_tag_alter_restaurant_options_post_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
    ]
