# Generated by Django 4.1.5 on 2023-01-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0008_image_alter_restaurant_options_remove_tag_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(max_length=1500),
        ),
    ]
