# Generated by Django 4.1.7 on 2023-03-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0008_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='SiteUsers',
        ),
    ]
