# Generated by Django 4.1.7 on 2023-03-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0009_rename_users_siteusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comment',
        ),
    ]
