# Generated by Django 4.1.5 on 2023-01-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0009_alter_post_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='Elite_eats_app.tag'),
        ),
    ]
