# Generated by Django 4.1.5 on 2023-01-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_eats_app', '0010_remove_restaurant_hashtag_post_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='Elite_eats_app.tag'),
        ),
    ]
